# Generated by Django 4.0.6 on 2022-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_images_image1_alter_images_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
